algorithm: supervised
save_dir: "./saved_models/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck':
  16}/lr-1e-4"
save_name: log
resume: true
load_path: "./saved_models/lora/supervised/clevr_count/10-shot/clip/dpr-0.2/train-aug-strong/{'lora_bottleneck':
  16}/lr-1e-4/log/latest_model.pth"
overwrite: true
use_tensorboard: true
use_wandb: false
epoch: 50
num_train_iter: 250
num_log_iter: 1
num_eval_iter: 100
batch_size: 16
eval_batch_size: 16
num_warmup_iter: 6
num_labels: 80
uratio: 1
ema_m: 0.0
hard_label: true
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0001
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: false
clip: 0.0
use_cat: true
net: timm/vit_base_patch16_clip_224.openai
net_from_name: false
data_dir: ./data
dataset: clevr_count
train_sampler: RandomSampler
num_classes: 8
num_workers: 4
seed: 0
world_size: 1
rank: 0
gpu: None
use_pretrain: true
# VTAB settings
train_split: train
eval_on_test: true
evaluate_unsupervised: false
es_patience: 0.0
peft_config:
  method_name: lora_1
  lora_bottleneck: 16
vit_config:
  drop_path_rate: 0.2
train_aug: strong
