algorithm: softmatch
save_dir: ./saved_models/adaptformer/softmatch/diabetic_retinopathy/80-shot/clip/lr-1e-5
save_name: log
resume: true
load_path: 
  ./saved_models/adaptformer/softmatch/diabetic_retinopathy/80-shot/clip/lr-1e-5/log/latest_model.pth
overwrite: true
use_tensorboard: true
use_wandb: false
epoch: 30
num_train_iter: 42780
num_log_iter: 356
num_eval_iter: 2852
batch_size: 32
eval_batch_size: 16
num_warmup_iter: 1069
num_labels: 400
uratio: 1
ema_m: 0.0
hard_label: true
T: 0.5
dist_align: true
dist_uniform: true
per_class: false
ema_p: 0.999
ulb_loss_ratio: 1.0
n_sigma: 2
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 1e-05
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: false
clip: 0.0
use_cat: true
net: timm/vit_base_patch16_clip_224.openai
net_from_name: false
data_dir: ./data
dataset: diabetic_retinopathy
train_sampler: RandomSampler
num_classes: 5
num_workers: 4
seed: 0
world_size: 1
rank: 0
dist_url: tcp://127.0.0.1:10086
dist_backend: nccl
gpu: None
use_pretrain: true
# VTAB settings
train_split: train
eval_on_test: true
evaluate_unsupervised: false
es_patience: 0.0
peft_config:
  method_name: adaptformer
  ft_mlp_module: adapter
  ft_mlp_mode: parallel
  ft_mlp_ln: before
  adapter_init: lora_kaiming
  adapter_bottleneck: 16
  adapter_scaler: 0.1
