algorithm: softmatch
save_dir: ./saved_models/lora/softmatch/kitti/5-shot/dinov2/lr-1e-5
save_name: log
resume: true
load_path: ./saved_models/lora/softmatch/kitti/5-shot/dinov2/lr-1e-5/log/latest_model.pth
overwrite: true
use_tensorboard: true
use_wandb: false
epoch: 30
num_train_iter: 6330
num_log_iter: 52
num_eval_iter: 422
batch_size: 32
eval_batch_size: 16
num_warmup_iter: 158
num_labels: 20
uratio: 1
ema_m: 0.0
hard_label: true
T: 0.5
dist_align: true
dist_uniform: true
per_class: false
ema_p: 0.999
ulb_loss_ratio: 1.0
n_sigma: 2
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 1e-05
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: false
clip: 0.0
use_cat: true
net: timm/vit_base_patch14_reg4_dinov2.lvd142m
net_from_name: false
data_dir: ./data
dataset: kitti
train_sampler: RandomSampler
num_classes: 4
num_workers: 4
seed: 0
world_size: 1
rank: 0
dist_url: tcp://127.0.0.1:10086
dist_backend: nccl
gpu: None
use_pretrain: true
# VTAB settings
train_split: train
eval_on_test: true
evaluate_unsupervised: false
es_patience: 0.0
peft_config:
  method_name: lora
  lora_bottleneck: 4
